### ISSUE TITLE
Upgrade PubNub dependency

### ISSUE THREAD

**Issue by manavo** [ringcentral/ringcentral-php#117]
PubNub is currently set to `^4.7.0`, but PubNub is up to `^6.0.0`.

Trying to update it seems to mostly work, other than requiring a UUID to be set:

```
PubNub\Exceptions\PubNubConfigurationException: UUID should not be empty

/Users/manavo/Code/ringcentral-php/vendor/pubnub/pubnub/src/PubNub/PubNub.php:115
/Users/manavo/Code/ringcentral-php/vendor/pubnub/pubnub/src/PubNub/PubNub.php:89
/Users/manavo/Code/ringcentral-php/src/Subscription/Subscription.php:408
/Users/manavo/Code/ringcentral-php/src/Subscription/Subscription.php:240
/Users/manavo/Code/ringcentral-php/src/Subscription/Subscription.php:154
/Users/manavo/Code/ringcentral-php/src/Subscription/SubscriptionTest.php:107
```

Adding a UUID [here](https://github.com/ringcentral/ringcentral-php/blob/master/src/Subscription/Subscription.php#L404) makes the tests pass, but I'm guessing the point would be to have a UUID set, persisted, and then reused, for each device/client.

Not that familiar with PubNub, so a bit reluctant to start a PR for this.

**Comment by tylerlong** [comment]
Is PubNub 4.7.0 not working or you just want to upgrade it?

**Comment by manavo** [comment]
I'm not even using PubNub, but I was running into the same issue as #118 where I use Laravel 10, and I couldn't upgrade from Laravel 9 to 10 because of the PubNub dependency.

I think one of the upstream dependencies of PubNub 4.7 is too out of date with Laravel 10. @coxlr might be able to confirm, if it's fresher in mind for them!

**Comment by manavo** [comment]
The workaround I've done for now is fork the repo, remove pubnub as a dependency (since I don't use it anyway) and I was able to upgrade to Laravel 10. But I'd much rather not have to maintain my own fork longer term...

**Comment by coxlr** [comment]
I added the below to the pull request, but adding here too, to answer the above question.

PubNub 4.0.0-alpha is the last version to be compatible with Laravel 10, due to Laravel 10 (the latest version) requiring monolog ^3.0, therefore the last compatible version of ringcentral-php is 2.2.5, as ^2.3.0 requires pubnub ^4.7.0 which use monolog ^1.1|^2.0. pubnub 6.0.0 added support for monolog ^3.0 which makes it compatible with Laravel 10.
So for the latest version of ringcentral-php to be compatible with Laravel 10 it needs to support pubnub ^6.0.0
