### ISSUE TITLE
Error message truncated in SDK 

### ISSUE THREAD

**Issue by samyukta0731** [ringcentral/ringcentral-php#133]
**Current behavior :**
Truncated error message are being displayed 

**for example** (please note, I know what the error message means and how to fix, but i am reporting this issue to state that only a part of the error message is being displayed)

Error: Client error: POST https://platform.ringcentral.com/analytics/calls/v1/accounts/~/aggregation/fetch?perPage=100 resulted in a 400 Bad Request response:
{"errors":[{"errorCode":"ANL-202","message":"OffsetDateTime (Text '2024-0-15T23:59:59.999Z' could not be parsed at index (truncated...)

**Expected behavior :**

This is a cURL response for the same error, cx expects to see a response that looks like the below, or shows the complete response. 

{
    "errors": [
        {
            "errorCode": "ANL-501",
            "message": "The datetime in 'timeFrom' field cannot be prior to 184 days from the current datetime"
        }
    ]
}

**Comment by tylerlong** [comment]
I believe this is the root cause: https://github.com/guzzle/guzzle/issues/2185

**Comment by ithieund** [comment]
Hello @tylerlong,
The truncated message is just a small issue which prevent the developer to read the real message.
The bigger problem is when the exception happen, how can we get the RAW JSON response from the server to handle the error properly.
Do you know the way to archive that result?
I already reported this issue via the Developer Support form and the support team said that I must add a comment in this ticket.

Hope you can give me a solution for this problem because without this SDK, we can get the raw JSON response from the API directly and easily using PHP curl. It's strange that an SDK cannot produce that output.
Thank you!

**Comment by SushilMallRC** [comment]
HI @ithieund @tylerlong , PR https://github.com/ringcentral/ringcentral-php/pull/139 merege into master, will let you once release new version.

**Comment by ithieund** [comment]
> HI @ithieund @tylerlong , PR #139 merege into master, will let you once release new version.

Hi @SushilMallRC , that's a good news. Thank you very much!

**Comment by SushilMallRC** [comment]
Hi @ithieund @samyukta0731 ,
A new version 3.0.3 has been released it contains the above changes.
