### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by ashitvora** [ringcentral/ringcentral-php#39]
I'm using dev-master version of SDK since I'm using it in Laravel 5.2 App.
When authenticating, I get an error related to missing Headers.

```
ApiException in Client.php line 54:
Client error: `POST https://platform.ringcentral.com/restapi/oauth/token` resulted in a `400 Bad Request` response:
{
"error" : "invalid_client",
"error_description" : "Authentication header value is malformed"
}
```

**Comment by tylerlong** [comment]
https://github.com/ringcentral/ringcentral-php/blob/master/src/Platform/Platform.php#L357
https://github.com/ringcentral/ringcentral-php/blob/master/src/Platform/Platform.php#L369

It probably means your appKey or appSecret is wrong.

**Comment by ashitvora** [comment]
Ah! my bad. I was passing password as extension and null as password.
But after fixing that typo, I get another error 

```
POST https://platform.devtest.ringcentral.com/restapi/oauth/token` resulted in a `400 Bad Request` response:
{
"error" : "unauthorized_client",
"error_description" : "Unauthorized for this grant type"
}
```


This happens when I try to authenticate the user.


All I'm doing is ...

```
public function __construct() {
		$ringcentral = new RingCentral(
			config('services.ringcentral.key'),
			config('services.ringcentral.secret'),
			config('app.env', 'production') === 'production' ? RingCentral::SERVER_PRODUCTION : RingCentral::SERVER_SANDBOX
		);

		$this->platform = $ringcentral->platform();
	}

	public static function make($data) {
		return new static();
	}

	public function auth($username = "", $extension = "", $password = "") {
		$auth = $this->platform->login($username, $extension, $password);
		dd($auth);
		print 'Authorized' . PHP_EOL;
       }
```

**Comment by tylerlong** [comment]
It probably means your app doesn't support password authorization flow.

Please logon https://developer.ringcentral.com and confirm that your app has the following configuration:

![image](https://cloud.githubusercontent.com/assets/733544/18026560/b93e5356-6c7d-11e6-92a9-d35d28325e69.png)

**Comment by ashitvora** [comment]
Apparently seems like password flow is not supported in Web/Server type platform.
I can't find any method to get auth url and then access and refresh token on successful authorization.

Can you point me to any doc related to OAuth flow in ringcentral?

**Comment by LingForCC** [comment]
@ashitvora Pls go to this [repo](https://github.com/grokify/ringcentral-demos-oauth). You could refer to the demo for php there.

**Comment by tylerlong** [comment]
Documentation is here: https://developer.ringcentral.com/api-docs/latest/index.html?section=Authentication.html#!#Authentication.html

**Comment by jatindergit** [comment]
@tylerlong I want to integrate ring central for one of my CRM(website) where our representatives can place call to leads. I have just tested ringcentral-php package and got success. 

BUT my concern is, if I am integrating ring central for my webiste(CRM) then I should create App with **Platform Type(Server/Web)** but it does not have password flow, therefore, for time being, I have created Mobile/iOS app and its working fine with ringcentral-php. 

I want your recommendation, that if I will continue the development with Platform Type(Mobile/iOS) app, then it will arise problem in future when I will make my app on production(Because I am using ring central for CRM **website**).
Or I should use **Platform Type(Server/Web)** for my CRM website and I will use ringcentral-demos-oauth to get the access token.

Please let me know your commendations.

Thanks
