### ISSUE TITLE
Unable to Refresh token

### ISSUE THREAD

**Issue by ashitvora** [ringcentral/ringcentral-php#40]
When I try to refresh the token, I get an error "Refresh Token has Expired".
After user authorized the app, I saved entire payload which had following info...

```
{
	"access_token": "*****",
	"token_type": "bearer",
	"expires_in": 3598,
	"refresh_token": *****",
	"refresh_token_expires_in": 604798,
	"scope": "ReadCallLog",
	"owner_id": "12345",
	"endpoint_id": "*****"
}
```

How can I have valid refresh token to call other apis?

**Comment by tylerlong** [comment]
The refresh token was valid at the time you got it. But later it expired. You should always remember to refresh it before it expires.

By the way, if you refresh it successfully, a new refresh token is returned and the current one expires automatically, so please remember to save the latest payload every time you refresh the token.

**Comment by ashitvora** [comment]
So if user authenticates today and if I dont make any request for next 24 hrs, I have to ask user to authenticate again (since I can not use access token or refresh token to get new access token).

In that case, I can do nothing if user does not explicitly take any action.

Is it? Or am I missing something here?

**Comment by LingForCC** [comment]
Yes. You are right. If user takes no actions, the refresh token will be expired in the end. You need to ask the user to re-login. BTW, according to the payload you pasted above, refresh token will be expired in 7 days.

**Comment by tylerlong** [comment]
> In that case, I can do nothing if user does not explicitly take any action.

That's not true. You can setup a cron job to refresh the tokens. refresh_token expires in 7 days, so you need to run the cron job at least once per week.

And there is something **tricky** you should be aware of: https://github.com/ringcentral/ringcentral-php/blob/master/src/Platform/Platform.php#L237  According to the source code, sometimes the sdk refreshes the token for you. If this happens, you'd have to save the new payload because the old one just expires. I think this is the root cause of the issue you posted.

In the C# Client, there is a token refresh event so programers can easily save the latest payload taking advantages of the listener design pattern. But there isn't such thing in this PHP SDK.   @anilkumarbp @kirill-konshin @grokify Please advise.
