### ISSUE TITLE
Demo code not working with the following steps..

### ISSUE THREAD

**Issue by BirdyUK** [ringcentral/ringcentral-php#53]
Hi,

I have performed the following steps:

> clone repo
> composer install
> change credentialsSample to credentials
> php index.php

And i get the following message after a few seconds:

[2017-11-18 01:06:54] PubNub.ERROR: cURL error 28: Operation timed out after 60015 milliseconds with 0 bytes received {"method":"Subscribe"} []

[2017-11-18 01:06:54] PubNub.DEBUG: GET https://ps.pndsn.com/v2/subscribe/sub-c-b8b9cd8c-e906-11e2-b383-02ee2ddab7fe/294679779839432_c55356a2/0?tt=2144983647&tr=3&pnsdk=PubNub-PHP%2F4.0.0&uuid=027DE65F-0267-4485-86A3-283E8EE2A9A7 {"method":"Subscribe"} []

The connection remains open but console continuously logs the above, I have tried to call the account number and extensions and neither of them work, Is their any ideas?

**Comment by anilkumarbp** [comment]
@BirdyUK : It might because `PubNub` is not responding within the given time. Hence you are seeing the error : 

>  Operation timed out after 60015 milliseconds with 0 bytes received {"method":"Subscribe"} []

Let me see if there is any problem in receiving notifications from Pubnub. However, in the meantime, if you are trying to set up `Subscription` using our API's, you could alternatively also look at creating the subscription using Webhooks

For more information, take a look at the below resources:

- [RingCentral API Reference on Subscriptions using Webhooks](https://developer.ringcentral.com/api-docs/latest/index.html#!#RefNotifications.html)
- [RingCentral Webhooks Quickstart Guide](http://ringcentral-quickstart.readthedocs.io/en/latest/webhooks/)
- [RingCentral Developer FAQ for Webhooks](http://ringcentral-faq.readthedocs.io/en/latest/notifications_subscriptions/)
