### ISSUE TITLE
Support to create Webhook subscription

### ISSUE THREAD

**Issue by embbnux** [ringcentral/ringcentral-php#59]
In this SDK, it only supports to create subscription with Pubnub. It should support to create webhook subscription.

https://developer.ringcentral.com/api-docs/latest/index.html#!#NotificationDeliveryModeRequest

**Comment by grokify** [comment]
What do you think a webhook helper would look like?

A PubNub helper can be useful because the PubNub subscription expires after 15 min and needs to be continually renewed.

A webhook subscription does not need to be renewed the same way. The steps are the following:

You make one REST API call to create the subscription (similar to other REST endpoints without specific helpers). If you wish to renew the webhook, add an event filter of the following format:

`/restapi/v1.0/subscription/%s?threshold=%d&interval=%d`

In your endpoint:
* Return the `Validation-Token` as a response header if present in the request.
* Renew the webhook by making another REST API call if the event is a renewal event.

In the above, how would a helper be useful?

Perhaps this should be an example app?

**Comment by grokify** [comment]
A webhook example app is here:

https://github.com/anilkumarbp/ringcentral-demos-webhooks/tree/master/php

We will look to add this to the tutorials list:

https://ringcentral.github.io/tutorials/

The `README.md` also has some basic info:

```php
$apiResponse = $sdk->platform()->post('/subscription', array(
    'eventFilters' => array(
        '/restapi/v1.0/account/~/extension/~/message-store',
        '/restapi/v1.0/account/~/extension/~/presence'
    ),
    'deliveryMode' => array(
        'transportType' => 'WebHook',
        'address' => 'https://consumer-host.example.com/consumer/path'
    )
));
```

**Comment by kirill-konshin** [comment]
Closing, described in doc
